# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{poe}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Khaja Minhajuddin"]
  s.date = %q{2010-11-08}
  s.default_executable = %q{poe}
  s.description = %q{utility to configure cijoe}
  s.email = %q{minhajuddin@cosmicvent.com}
  s.executables = ["poe"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/poe",
     "hooks/build-failed",
     "hooks/build-worked",
     "hooks/common.rb",
     "hooks/post-update",
     "lib/poe.rb",
     "poe.gemspec",
     "poe.yml",
     "test/helper.rb",
     "test/test_poe.rb"
  ]
  s.homepage = %q{http://github.com/minhajuddin/poe}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{utility to configure cijoe}
  s.test_files = [
    "test/test_poe.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<cijoe>, [">= 0"])
    else
      s.add_dependency(%q<cijoe>, [">= 0"])
    end
  else
    s.add_dependency(%q<cijoe>, [">= 0"])
  end
end

