#!/usr/bin/env ruby
require File.join(File.dirname(__FILE__), 'common')

#TODO include the name of the project in the subject
send_mail :subject => "FAIL: Build failed for #{ENV['SHA']} #{ENV['MESSAGE']}"
