#!/usr/bin/env ruby
require File.join(File.dirname(__FILE__), 'common')

#TODO include the name of the project in the subject
Notifier.new.send_mail :subject => "OK: Build successful for #{ENV['SHA']} #{ENV['MESSAGE']}"
